# Makefile

include ../../make.inc

default: title all

all: run 

run:
	${PARA_PREFIX} ${PYT} test.py

clean:
	- /bin/rm -rf *out *yml

title:
	@echo " "
	@echo "##############################"
	@echo "### test1 : Basic import ###"
	@echo "##############################"
	@echo " "
