# Makefile

include ../../make.inc

default: title all

all: run 

run:
	${PARA_PREFIX} ${PYT} demo.py

clean:
	- /bin/rm -rf *out *yml

title:
	@echo " "
	@echo "##############################"
	@echo "### demo1 : Basic rearrange ##"
	@echo "##############################"
	@echo " "
